### PR TITLE
fix compilation on macos

### PR DESCRIPTION
**Pull request by anuejn**

### CODE REVIEW

**Comment by rroohhh** [comment]
maybe we just want to disable openmp on macos for now? To me it seems like the stock macos clang doesn't support it, and we probably don't want to require users to use a custom clang, right?

**Comment by anuejn** [comment]
seems like a good idea

**Comment by anuejn** [comment]
so this should work now @rroohhh

**Review by rroohhh — APPROVED** [review]
lgtm, maybe we want to provide some feedback to the users on macos that enabling openmp actuall does nothing (in the high level api)?

**Pull request merged**
